# Generated by Django 2.2.1 on 2019-06-03 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190603_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('angle', models.IntegerField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_positions', to='api.Result')),
            ],
            options={
                'db_table': 'text_position',
            },
        ),
    ]
